apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
  namespace: my-app
data:
  application.properties: |
    server.port=8080
    spring.datasource.username=bloguser
    spring.datasource.password=${MYSQL_PASSWORD}
    spring.datasource.url=jdbc:mysql://mysql:3306/blogdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    spring.jpa.hibernate.ddl-auto=validate
    spring.sql.init.mode=embedded
    spring.flyway.user=bloguser
    spring.flyway.password=${MYSQL_PASSWORD}
    secret.key=47A52F686696CABA4A9824E6177DFFFF5161ASDFDS1D2DS
    file.upload-dir=/app/files
    spring.servlet.multipart.enabled=true
    spring.servlet.multipart.max-file-size=10MB
    spring.servlet.multipart.max-request-size=10MB
    spring.elasticsearch.uris=http://elasticsearch:9200
    spring.elasticsearch.username=admin
    spring.elasticsearch.password=${ELASTICSEARCH_PASSWORD}
    spring.data.elasticsearch.connect-timeout=10000
    spring.data.elasticsearch.socket-timeout=60000