apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: baturayacarturk/blog-application:1.0.0-21
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: blog-config
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blog-secrets
              key: mysql-root-password
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blog-secrets
              key: ELASTICSEARCH_PASSWORD
        volumeMounts:
        - name: file-upload
          mountPath: /app/files
      volumes:
      - name: file-upload
        emptyDir: {}