apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: baturayacarturk/blog-application:1.0.0-21
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: blog-secrets
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: upload-volume
          mountPath: /app/files
      volumes:
      - name: config-volume
        configMap:
          name: blog-config
      - name: upload-volume
        emptyDir: {}